package scenario

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"
)

// residualsJSON is the fitted empirical residual distribution, generated by
// edge/model/analysis/fit_residuals.py and committed alongside this package.
//
// Embedding rather than reading from disk keeps edgectl a single self-contained
// binary with no runtime data dependency, and makes a model refresh a data
// change reviewed in a diff rather than a file that might or might not be
// present on the machine that needs it.
//
//go:embed artifacts/residuals.json
var residualsJSON []byte

// Residuals is one fitted distribution of actual-minus-expected.
//
// The sign convention deliberately lives with the caller: CDF is indexed by
// "actual minus expected", so this table does not encode whether a -3 spread
// means the home team is favoured. FromSpread computes the expectation under
// its own convention and then applies this.
type Residuals struct {
	N              int         `json:"n"`
	FitFirstSeason int         `json:"fit_first_season"`
	FitLastSeason  int         `json:"fit_last_season"`
	Mean           float64     `json:"mean"`
	SD             float64     `json:"sd"`
	Points         int         `json:"points"`
	CDF            [][]float64 `json:"cdf"` // [[residual, P(X <= residual)], ...]
}

// ResidualModel is the whole artifact.
type ResidualModel struct {
	GeneratedAt string    `json:"generated_at"`
	GeneratedBy string    `json:"generated_by"`
	Total       Residuals `json:"total"`
	Margin      Residuals `json:"margin"`
}

var (
	modelOnce sync.Once
	model     *ResidualModel
	modelErr  error
)

// Model returns the embedded residual model, parsed once.
//
// A malformed or empty artifact is an error rather than an empty model. The
// alternative -- a zero-valued CDF that silently reports every probability as
// 0 or 1 -- is exactly the class of failure this package exists to avoid.
func Model() (*ResidualModel, error) {
	modelOnce.Do(func() {
		var m ResidualModel
		if err := json.Unmarshal(residualsJSON, &m); err != nil {
			modelErr = fmt.Errorf("scenario: parsing embedded residuals: %w", err)
			return
		}
		if err := m.Total.validate("total"); err != nil {
			modelErr = err
			return
		}
		if err := m.Margin.validate("margin"); err != nil {
			modelErr = err
			return
		}
		model = &m
	})
	return model, modelErr
}

func (r Residuals) validate(name string) error {
	if len(r.CDF) < 2 {
		return fmt.Errorf("scenario: %s residuals have %d points, need at least 2", name, len(r.CDF))
	}
	if r.N <= 0 {
		return fmt.Errorf("scenario: %s residuals report n=%d", name, r.N)
	}
	prevX, prevP := r.CDF[0][0], r.CDF[0][1]
	for i, pt := range r.CDF {
		if len(pt) != 2 {
			return fmt.Errorf("scenario: %s residual point %d has %d fields, want 2", name, i, len(pt))
		}
		x, p := pt[0], pt[1]
		if p < 0 || p > 1 {
			return fmt.Errorf("scenario: %s residual point %d has probability %v", name, i, p)
		}
		if i > 0 {
			if x <= prevX {
				return fmt.Errorf("scenario: %s residuals not sorted at point %d (%v after %v)",
					name, i, x, prevX)
			}
			if p < prevP {
				return fmt.Errorf("scenario: %s CDF decreases at point %d (%v after %v)",
					name, i, p, prevP)
			}
		}
		prevX, prevP = x, p
	}
	if last := r.CDF[len(r.CDF)-1][1]; last < 0.999 {
		return fmt.Errorf("scenario: %s CDF tops out at %v, not 1", name, last)
	}
	return nil
}

// CDFAt returns P(residual <= x), linearly interpolated between tabulated
// points.
//
// Football residuals take few distinct values -- scores are integers and lines
// move in half points -- so the table is the exact empirical CDF at every value
// observed, roughly 150 points, rather than a sampled grid. Interpolation only
// fills the gaps between adjacent observed values.
//
// This mirrors cdf_lookup in fit_residuals.py; both are exercised against the
// same fixtures so a divergence between the languages fails a test rather than
// quietly changing a probability.
func (r Residuals) CDFAt(x float64) float64 {
	n := len(r.CDF)
	if n == 0 {
		return 0
	}
	if x < r.CDF[0][0] {
		return 0
	}
	if x >= r.CDF[n-1][0] {
		return 1
	}
	lo, hi := 0, n-1
	for lo < hi-1 {
		mid := (lo + hi) / 2
		if r.CDF[mid][0] <= x {
			lo = mid
		} else {
			hi = mid
		}
	}
	x0, p0 := r.CDF[lo][0], r.CDF[lo][1]
	x1, p1 := r.CDF[hi][0], r.CDF[hi][1]
	if x1 == x0 {
		return p1
	}
	return p0 + (p1-p0)*(x-x0)/(x1-x0)
}

// SurvivalAt returns P(residual > x).
func (r Residuals) SurvivalAt(x float64) float64 { return 1 - r.CDFAt(x) }
