package draft

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// leanDir writes named sets into a throwaway config directory.
func leanDir(t *testing.T, files map[string]string) string {
	t.Helper()
	cfg := t.TempDir()
	dir := filepath.Join(cfg, leansDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name+".csv"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return cfg
}

const mineCSV = `player,lean,cap,note
Kenneth Walker,must,,situation
Chase Brown,up,,
`

const mentonCSV = `# generated by draftroom leans -generate on 2026-08-06
player,lean,cap,note
Kenneth Walker,down,,zero traits
Breece Hall,down,,zero traits
Chase Brown,up,,one trait
`

// TestPrecedenceIsTheOrderYouListThem — the whole contract of -leans.
func TestPrecedenceIsTheOrderYouListThem(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV, "menton": mentonCSV})

	mineFirst, _, err := LoadLeanSets(cfg, []string{"mine", "menton"})
	if err != nil {
		t.Fatal(err)
	}
	walker := mineFirst[normalizeName("Kenneth Walker")]
	if walker.Lean != LeanMust || walker.Source != "mine" {
		t.Errorf("mine listed first should win: got %s from %s", walker.Lean, walker.Source)
	}

	mentonFirst, _, err := LoadLeanSets(cfg, []string{"menton", "mine"})
	if err != nil {
		t.Fatal(err)
	}
	walker = mentonFirst[normalizeName("Kenneth Walker")]
	if walker.Lean != LeanDown || walker.Source != "menton" {
		t.Errorf("menton listed first should win: got %s from %s", walker.Lean, walker.Source)
	}
}

// TestLosingReadsSurviveTheMerge — a merge that discarded them could not
// tell you that you are outvoting someone.
func TestLosingReadsSurviveTheMerge(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV, "menton": mentonCSV})
	merged, _, err := LoadLeanSets(cfg, []string{"mine", "menton"})
	if err != nil {
		t.Fatal(err)
	}

	walker := merged[normalizeName("Kenneth Walker")]
	if len(walker.Others) != 1 {
		t.Fatalf("expected menton's read kept, got %+v", walker.Others)
	}
	if walker.Others[0].Lean != LeanDown || walker.Others[0].Source != "menton" {
		t.Errorf("wrong second opinion: %+v", walker.Others[0])
	}
	if !walker.Contested() {
		t.Error("must vs down is a disagreement")
	}
	if !strings.Contains(walker.Why(), "menton: down") {
		t.Errorf("Why() should name the dissenter: %q", walker.Why())
	}
}

// TestAgreementIsNotContested — both sets liking a player is not a conflict,
// or every shared read would be flagged and the flag would mean nothing.
func TestAgreementIsNotContested(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV, "menton": mentonCSV})
	merged, _, err := LoadLeanSets(cfg, []string{"mine", "menton"})
	if err != nil {
		t.Fatal(err)
	}

	brown := merged[normalizeName("Chase Brown")]
	if len(brown.Others) != 1 {
		t.Fatalf("menton's read should still be recorded: %+v", brown.Others)
	}
	if brown.Contested() {
		t.Error("up and up is agreement, not a conflict")
	}
	if contested := merged.Contested(); len(contested) != 1 {
		t.Errorf("expected only Walker contested, got %d", len(contested))
	}
}

// TestMustAndUpAgree — a difference of degree between people on the same
// side is not a disagreement about the player.
func TestMustAndUpAgree(t *testing.T) {
	cases := []struct {
		mine, theirs Lean
		contested    bool
	}{
		{LeanMust, LeanUp, false},
		{LeanUp, LeanMust, false},
		{LeanDown, LeanDND, false},
		{LeanMust, LeanDown, true},
		{LeanUp, LeanDND, true},
		{LeanDND, LeanUp, true},
	}
	for _, c := range cases {
		pl := PlayerLean{Player: "X", Lean: c.mine, Source: "mine",
			Others: []PlayerLean{{Lean: c.theirs, Source: "them"}}}
		if got := pl.Contested(); got != c.contested {
			t.Errorf("%s vs %s: contested = %v, want %v", c.mine, c.theirs, got, c.contested)
		}
	}
}

// TestUnknownSetIsAnError — a typo must not silently drop every read in the
// set you meant to load.
func TestUnknownSetIsAnError(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV})
	_, _, err := LoadLeanSets(cfg, []string{"mine", "mentn"})
	if err == nil {
		t.Fatal("a misspelled set should be an error")
	}
	if !strings.Contains(err.Error(), "mentn") {
		t.Errorf("the error should name the missing set: %v", err)
	}
}

// TestSetNamesRejectsPaths keeps -leans a set name rather than a way to read
// an arbitrary file.
func TestSetNamesRejectsPaths(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV})
	for _, bad := range []string{"../mine", "sub/mine", ".hidden", ""} {
		if _, err := LoadLeanSet(cfg, bad); err == nil {
			t.Errorf("%q should not be a valid set name", bad)
		}
	}
}

// TestGeneratedMarkerIsRead — whether a file may be overwritten depends on
// it, so misreading it destroys hand-written work.
func TestGeneratedMarkerIsRead(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV, "menton": mentonCSV})
	sets := map[string]bool{}
	_, loaded, err := LoadLeanSets(cfg, []string{"mine", "menton"})
	if err != nil {
		t.Fatal(err)
	}
	for _, s := range loaded {
		sets[s.Name] = s.Generated
	}
	if sets["mine"] {
		t.Error("a hand-written set must not read as generated")
	}
	if !sets["menton"] {
		t.Error("the generated marker was not recognised")
	}
}

// TestCommentsAreSkipped — generated files carry a provenance header.
func TestCommentsAreSkipped(t *testing.T) {
	got, err := ParseLeans(strings.NewReader(mentonCSV))
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Errorf("read %d leans past the comment header, want 3", len(got))
	}
}

// TestContestedReachesTheWire — the page cannot recompute which leans
// contradict which, so the JSON has to carry it.
func TestContestedReachesTheWire(t *testing.T) {
	pl := PlayerLean{Player: "Kenneth Walker", Lean: LeanMust, Source: "mine",
		Others: []PlayerLean{{Lean: LeanDown, Source: "menton"}}}

	raw, err := json.Marshal(pl)
	if err != nil {
		t.Fatal(err)
	}
	var wire struct {
		Lean        string   `json:"-"`
		Contested   bool     `json:"contested"`
		ContestedBy []string `json:"contestedBy"`
	}
	if err := json.Unmarshal(raw, &wire); err != nil {
		t.Fatal(err)
	}
	if !wire.Contested {
		t.Errorf("contested did not reach the wire: %s", raw)
	}
	if len(wire.ContestedBy) != 1 || !strings.Contains(wire.ContestedBy[0], "menton") {
		t.Errorf("contestedBy = %v, want it to name menton", wire.ContestedBy)
	}
	// The fields the board already reads must still be there.
	if !strings.Contains(string(raw), `"Player":"Kenneth Walker"`) {
		t.Errorf("the custom marshaller dropped existing fields: %s", raw)
	}
}

// TestUncontestedOmitsTheField keeps the common row small.
func TestUncontestedOmitsTheField(t *testing.T) {
	raw, err := json.Marshal(PlayerLean{Player: "X", Lean: LeanUp, Source: "mine"})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), "contestedBy") {
		t.Errorf("an uncontested lean should not carry the list: %s", raw)
	}
}

func TestSetNamesSplitsTheFlag(t *testing.T) {
	got := SetNames(" mine , menton ,, ")
	if len(got) != 2 || got[0] != "mine" || got[1] != "menton" {
		t.Errorf("SetNames = %v", got)
	}
}

// TestDuplicateSetIsLoadedOnce — "mine,mine" must not make a set argue with
// itself.
func TestDuplicateSetIsLoadedOnce(t *testing.T) {
	cfg := leanDir(t, map[string]string{"mine": mineCSV})
	merged, sets, err := LoadLeanSets(cfg, []string{"mine", "mine"})
	if err != nil {
		t.Fatal(err)
	}
	if len(sets) != 1 {
		t.Errorf("loaded the same set %d times", len(sets))
	}
	if walker := merged[normalizeName("Kenneth Walker")]; len(walker.Others) != 0 {
		t.Errorf("a set disagreed with itself: %+v", walker.Others)
	}
}
