package draft

import (
	"bufio"
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// generatedMarker opens every generated lean set. It is how the tool knows
// a file may be rewritten: anything without it was typed by a person, and
// regenerating over the top of that would destroy work.
const generatedMarker = "# generated by draftroom leans -generate"

// isGenerated reports whether a lean file was produced by this tool.
func isGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	line, err := bufio.NewReader(f).ReadString('\n')
	if err != nil && line == "" {
		return false
	}
	return strings.HasPrefix(strings.TrimSpace(line), generatedMarker)
}

// LeanGenerator turns a source file into a lean set.
type LeanGenerator struct {
	// Name is the set's file stem.
	Name string
	// Source is the normalized CSV it reads, relative to the data root.
	Source string
	// What explains, in one line, what the generated leans mean.
	What string
	// Build produces the reads.
	Build func(rows []map[string]string) ([]PlayerLean, error)
}

// Generators are the lean sets that can be rebuilt from source data.
//
// Only analyst sets appear here. Your own reads are not derived from
// anything and are never regenerated.
var Generators = []LeanGenerator{{
	Name:   "menton",
	Source: "fantasypoints-big3-2026.csv",
	What: "Kyle Menton's Big-3 traits: receiving volume, explosive rate, " +
		"and goal-line work. Backs who hit two of the three lean up; backs " +
		"who hit none lean down.",
	Build: mentonLeans,
}}

// GeneratorNamed finds a generator by set name.
func GeneratorNamed(name string) (LeanGenerator, bool) {
	for _, g := range Generators {
		if g.Name == name {
			return g, true
		}
	}
	return LeanGenerator{}, false
}

// mentonLeans reads the Big-3 traits.
//
// The threshold is two of three rather than one, because one is the common
// case — most backs are good at something — and a lean that fires on
// almost everyone says nothing. Menton's argument is specifically about
// backs who combine traits, and on the 2026 field that is a short list.
//
// Zero traits leans down for the mirror-image reason: a back with none of
// them is being drafted on situation or reputation. That is not always
// wrong, and it is exactly the kind of claim worth seeing your own reads
// argue with.
func mentonLeans(rows []map[string]string) ([]PlayerLean, error) {
	var out []PlayerLean
	for _, row := range rows {
		name := strings.TrimSpace(row["player"])
		if name == "" {
			continue
		}
		raw := strings.TrimSpace(row["traits_hit"])
		if raw == "" {
			return nil, fmt.Errorf("%s has no traits_hit column value", name)
		}
		hits, err := strconv.Atoi(raw)
		if err != nil {
			return nil, fmt.Errorf("%s: bad traits_hit %q: %w", name, raw, err)
		}

		var lean Lean
		switch {
		case hits >= 2:
			lean = LeanUp
		case hits == 0:
			lean = LeanDown
		default:
			// Exactly one trait is the middle of the field: no read.
			continue
		}
		out = append(out, PlayerLean{
			Player: name,
			Lean:   lean,
			Note:   mentonNote(hits, row),
			Source: "menton",
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Player < out[j].Player })
	return out, nil
}

// mentonNote says which traits produced the read, so the board can show a
// reason rather than a verdict.
func mentonNote(hits int, row map[string]string) string {
	if hits == 0 {
		return fmt.Sprintf("Big-3: none — %s rec, %s explosive, %s inside-10 per game",
			row["rec_fpg"], row["explosive_fpg"], row["inside10_fpg"])
	}
	var hit []string
	for _, t := range []struct{ col, label string }{
		{"hits_receiving", "receiving"},
		{"hits_explosive", "explosive"},
		{"hits_goal_line", "goal line"},
	} {
		if strings.TrimSpace(row[t.col]) == "1" {
			hit = append(hit, t.label)
		}
	}
	return fmt.Sprintf("Big-3: %d of 3 — %s", hits, strings.Join(hit, " + "))
}

// Generate builds a lean set and returns the reads it produced.
func (g LeanGenerator) Generate(root DataRoot) ([]PlayerLean, error) {
	rows, err := readCSVRows(root.Normalized(g.Source))
	if err != nil {
		return nil, fmt.Errorf("draft: generating %s leans: %w", g.Name, err)
	}
	leans, err := g.Build(rows)
	if err != nil {
		return nil, fmt.Errorf("draft: generating %s leans: %w", g.Name, err)
	}
	return leans, nil
}

// WriteLeanSet writes a generated set to the config directory.
//
// It refuses to overwrite a file that was not generated, which is the guard
// that keeps a regeneration from eating hand-written reads — the failure
// mode this whole split exists to prevent.
func WriteLeanSet(configDir string, g LeanGenerator, leans []PlayerLean) (string, error) {
	dir := filepath.Join(configDir, leansDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("draft: %w", err)
	}
	path := filepath.Join(dir, g.Name+".yaml")
	// Both formats are guarded, not just the one being written: a set that
	// used to be a hand-written CSV must not be quietly replaced by a
	// generated YAML file sitting in front of it.
	stale := filepath.Join(dir, g.Name+".csv")
	for _, p := range []string{path, stale} {
		if _, err := os.Stat(p); err == nil && !isGenerated(p) {
			return "", fmt.Errorf("draft: %s was not generated by this tool and will not be overwritten"+
				"\nmove it aside if you meant to replace it", p)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s on %s\n", generatedMarker, time.Now().Format("2006-01-02"))
	fmt.Fprintf(&b, "# source: %s\n", g.Source)
	for _, line := range wrapComment(g.What, 72) {
		fmt.Fprintf(&b, "# %s\n", line)
	}
	fmt.Fprintf(&b, "# edits here are lost on the next -generate; put your own reads in mine.yaml\n")

	doc, err := FormatLeansYAML(leans, nil)
	if err != nil {
		return "", err
	}
	b.Write(doc)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("draft: %w", err)
	}
	// The CSV this set used to be would otherwise sit alongside forever,
	// loaded by nothing and drifting out of date.
	if isGenerated(stale) {
		os.Remove(stale)
	}
	return path, nil
}

// wrapComment breaks a sentence across comment lines at word boundaries.
func wrapComment(s string, width int) []string {
	var out []string
	line := ""
	for _, word := range strings.Fields(s) {
		if line != "" && len(line)+1+len(word) > width {
			out, line = append(out, line), ""
		}
		if line == "" {
			line = word
			continue
		}
		line += " " + word
	}
	if line != "" {
		out = append(out, line)
	}
	return out
}

// readCSVRows reads a CSV into per-row maps keyed by lowercased header.
func readCSVRows(path string) ([]map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	cr := csv.NewReader(f)
	cr.FieldsPerRecord = -1
	cr.TrimLeadingSpace = true

	header, err := cr.Read()
	if err == io.EOF {
		return nil, fmt.Errorf("%s is empty", path)
	}
	if err != nil {
		return nil, err
	}
	for i, h := range header {
		header[i] = strings.ToLower(strings.TrimSpace(h))
	}

	var out []map[string]string
	for {
		rec, err := cr.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		row := make(map[string]string, len(header))
		for i, h := range header {
			if i < len(rec) {
				row[h] = rec[i]
			}
		}
		out = append(out, row)
	}
	return out, nil
}
