// Package board holds the per-week line board: the prices you have actually
// seen, per sportsbook, for every game on the schedule.
//
// The board exists so line shopping stops being a manual exercise. Every
// decision it feeds -- which dog converts best as a bonus bet, which parlay
// legs stay disjoint, where one book is out of line with the rest -- is
// arithmetic over prices. Only the bookkeeping was ever hard.
//
// Prices are stored as the strings they were typed as, not as parsed numbers.
// That is deliberate. Most cells are empty and stay empty forever, and an
// empty cell must round-trip through the file untouched rather than becoming
// a zero that looks like a price. Parsing happens at the point of use, where
// a malformed value can be reported against the game it belongs to.
package board

import (
	"fmt"
	"io"
	"sort"

	"gopkg.in/yaml.v3"
)

// Doc is one week's file.
type Doc struct {
	Season int              `yaml:"season"`
	Week   int              `yaml:"week"`
	Games  map[string]*Game `yaml:"games"`
}

// Game is one matchup and every book's prices for it. The map key in Doc.Games
// is the nflverse game_id (e.g. "2026_01_NYJ_TEN"), which is stable across
// schedule reissues and is what games.csv joins on.
type Game struct {
	Away    string           `yaml:"away"`
	Home    string           `yaml:"home"`
	Kickoff string           `yaml:"kickoff"`
	Books   map[string]Lines `yaml:"books"`
}

// Lines is one book's three markets for one game. All three are optional; a
// blank string means "no price recorded", which is the normal state.
type Lines struct {
	ML     string `yaml:"ml"`
	Spread string `yaml:"spread"`
	Total  string `yaml:"total"`
}

// Empty reports whether this book has no prices at all for the game.
func (l Lines) Empty() bool { return l.ML == "" && l.Spread == "" && l.Total == "" }

// Books are the sportsbooks a scaffolded file carries a slot for. Adding one
// here adds an empty slot to every game on the next scaffold run.
//
// These are deliberately plain strings and NOT wager.Book. wager.Book carries
// bonus-bet safety rules -- whether a push forfeits the bonus, whether a token
// can be split -- and wager.CheckBonusMarket hard-fails for any book whose
// rules are not recorded. That hard failure is protective: clearing a wager at
// a book whose push behaviour is unknown is the exact mistake it exists to
// prevent. Fanatics and Caesars have no recorded rules, so they must not
// become wager.Book values just to appear on a board. Line shopping needs a
// label; it does not need, and must not silently acquire, a safety clearance.
var Books = []string{
	"consensus",
	"fanatics",
	"draftkings",
	"fanduel",
	"betmgm",
	"caesars",
	"bet365",
}

// Consensus is the book key holding the closing/consensus line carried in
// games.csv. It is prefilled by the scaffold and is a reference column, not a
// place you can bet.
const Consensus = "consensus"

// Parse reads a week file.
func Parse(r io.Reader) (*Doc, error) {
	dec := yaml.NewDecoder(r)
	// An unknown field is a typo, and silently dropping it would lose every
	// price underneath -- the same reasoning as ParseLeansYAML in league_home.
	dec.KnownFields(true)

	var d Doc
	if err := dec.Decode(&d); err != nil {
		return nil, fmt.Errorf("board: %w", err)
	}
	if d.Games == nil {
		d.Games = map[string]*Game{}
	}
	return &d, nil
}

// header is re-emitted on every write because yaml.v3 does not preserve
// comments through a decode/encode cycle. The file is generated, so the
// documentation has to be generated with it.
const header = `# Week %02d, %d. Generated by ` + "`edgectl board scaffold`" + ` from games.csv.
#
# Prices are American odds, exactly as the book shows them. Leave a book blank
# until you have its number -- empty is the normal state and is never an error.
# A malformed value IS an error; run ` + "`edgectl board validate`" + ` to find them.
#
#   ml:     away/home                  e.g. 130/-155
#   spread: line away_odds/home_odds   e.g. 2.5 -110/-110   (line is the AWAY spread)
#   total:  line over/under            e.g. 44.5 -110/-110
#
# consensus is the closing line from games.csv, prefilled as a reference
# column. It is not a book you can bet.
`

// Encode writes a week file, header first.
func (d *Doc) Encode(w io.Writer) error {
	if _, err := fmt.Fprintf(w, header, d.Week, d.Season); err != nil {
		return err
	}
	enc := yaml.NewEncoder(w)
	enc.SetIndent(2)
	if err := enc.Encode(d); err != nil {
		return fmt.Errorf("board: %w", err)
	}
	return enc.Close()
}

// GameIDs returns the game ids sorted by kickoff, then id.
//
// Sorted output matters twice over: the UI shows games in the order they are
// played rather than alphabetically, and a stable order keeps regenerated
// files diffable. The map itself is unordered, and yaml.v3 encodes map keys
// alphabetically, so kickoff order has to be applied by callers who want it.
func (d *Doc) GameIDs() []string {
	ids := make([]string, 0, len(d.Games))
	for id := range d.Games {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool {
		a, b := d.Games[ids[i]], d.Games[ids[j]]
		if a.Kickoff != b.Kickoff {
			return a.Kickoff < b.Kickoff
		}
		return ids[i] < ids[j]
	})
	return ids
}

// Coverage counts how many games in this week carry a moneyline for each book.
//
// A board is partly filled almost all of the time: a week is ~16 games across
// seven books, and nobody finishes that in one sitting. Coverage exists so
// callers can say what they do not know instead of quietly reporting on
// whatever happens to be entered.
//
// Only the moneyline is counted. It is the market every other number is
// derived from here -- dogs, conversions and parlays are all moneyline work --
// so a game with a spread but no moneyline contributes nothing to a report
// and should not read as covered.
func (d *Doc) Coverage() map[string]int {
	out := make(map[string]int, len(Books))
	for _, bk := range Books {
		out[bk] = 0
	}
	for _, g := range d.Games {
		for bk, l := range g.Books {
			if _, ok, err := ParseMarket(l.ML); ok && err == nil {
				out[bk]++
			}
		}
	}
	return out
}

// BettableBooks lists the books with at least one price this week, excluding
// consensus.
//
// Consensus is generated from the schedule and cannot be wagered, so counting
// it as a book is what turns "best available price" into a sentence about a
// number you cannot take. With fewer than two of these there is nothing to
// shop, however many rows a comparison would produce.
func (d *Doc) BettableBooks() []string {
	cov := d.Coverage()
	var out []string
	for _, bk := range Books {
		if bk != Consensus && cov[bk] > 0 {
			out = append(out, bk)
		}
	}
	return out
}
